### ISSUE TITLE
Getting the PAE Matrix ?

### ISSUE THREAD

**Issue by tubiana** [samuelmurail/af2_analysis#3]
Hi @samuelmurail !

It seems that now it's not possible to extract the PAE patrix directly (before the `get_pae()` function was accessible, not anymore), or did you put it in another function :) ? 

Also, an extra request.. Your tool is great to analyse a lot of models, but the `tqdm` bar make it not so nice to use in a notebook on tons of models :-p It would be great if we can have the possibility to hide it ^^

Suggestion not super clean but it might work... : 

```python
 def __init__(self, directory=None, csv=None, silent=False):
    if silent == True:
        tqdm = for
```

**Comment by samuelmurail** [comment]
Hi @tubiana,

Thanks for the feedback !

Yes `get_pae()` is no more a method of `Data` class, it is now a simple function which takes the json file path as argument.

Considering your remark about tqdm bar, I have added an option `verbose=True` in class constructor and in all analysis module. If you define `verbose=False` it will hide the tqdm bar.

Let me know if it works.

By the way if ou are intersted in PAE matrix interpretation, I have added the LIS (https://github.com/flyark/AFM-LIS) score which seems to work great.

Cheers,
Samuel

**Comment by tubiana** [comment]
Hi @samuelmurail ! 

Ok thank you :) Great for the LIS score! This will be very usefull to score my protein complexes!
I wanted to plot the pae only to regenerate missing graphs from AF3 models output, but now I understood how to do it from the dataframe :)

Cheers, 
Thibault.
