### ISSUE TITLE
Confidence on LIS scoring ?

### ISSUE THREAD

**Issue by tubiana** [samuelmurail/af2_analysis#4]
Hi @samuelmurail :)

Just asking if you found any inconsistencies in the computation of the LIS score ? 

Here's for example the LIS score matrix from a model I made with af2_analysis : 
![image](https://github.com/user-attachments/assets/d95f43db-7733-4056-b15b-21c56f435e31)

And the LIS score from the original notebook : 
![image](https://github.com/user-attachments/assets/1a489968-250b-4918-a31a-b939d6e543d6)

Or maybe there is something I misunderstood on af2_analysis LIS matrix :) ?

Cheers,
Thibault

**Comment by samuelmurail** [comment]
Hi @tubiana 

I tested it on my side. I guess you are not using the same versions of the library `af2_analysis` in the two cases.
I made a lot of change before summer holidays, that may explain your issue.

Here is how to use it:

```
# Import your models
my_data = af2_analysis.Data('./src/af2_analysis/test/inputs/beta_amyloid_dimer_cf_1.5.5/', verbose=False)
#compute_LIS_pep
docking.LIS_pep(my_data, verbose=False)
```

You should have a matrix for the `LIS` field of size $N \times N$ where $N$ is the number of chain of your model.
And you should also have access to the `LIS_rec_pep` `LIS_pep_rec` values which are floating values.

I have updated the `example.ipynb` if it can help. Let me know if your inconsistencies are fixed.

Cheers,
Samuel
